### ISSUE TITLE
passwords are incorrect

### ISSUE THREAD

**Issue by phanikumarvarikuti** [csalab-id/csaf#1]
we are getting password was incorrect

**Comment by redhawkeye** [comment]
Can you give me a proof?
Specific service or application?

**Comment by phanikumarvarikuti** [comment]
hi password was working ChangeMePlease
  http://wackopicko.lab/ and http://purpleops.lab/  both labs are not accessible

**Comment by redhawkeye** [comment]
No, wackopicko and Purpleops are not set on environment.
You can see Purpleops password from README.md
Then open the Wackopicko repo for password reference.
https://github.com/adamdoupe/WackoPicko

**Comment by phanikumarvarikuti** [comment]
thanks but Wackopicko and Purpleops both are not opening? remeaning all are accessible

**Comment by redhawkeye** [comment]
Can you give me all the logs from Wackopicko and Purpleops services?
You can send me proof like a screenshot or related field.
An hour later, I worked on the purpleops issue which should fixed for incomplete services.
You can remove and pull Purpleop's image again.

**Comment by phanikumarvarikuti** [comment]
can you guide me to gather the logs I will forward

**Comment by redhawkeye** [comment]
docker-compose logs wackopicko
docker-compose logs purpleops

**Comment by phanikumarvarikuti** [comment]
[wackopicko.txt](https://github.com/csalab-id/csaf/files/14067425/wackopicko.txt)
[purpleops.txt](https://github.com/csalab-id/csaf/files/14067465/purpleops.txt)


please find the logs

**Comment by redhawkeye** [comment]
Please type this command to fix the incomplete services

```
docker-compose stop wackopicko purpleops mongodb
docker-compose rm -f wackopicko purpleops mongodb
docker volume rm csaf_purpleops csaf_mongodb_configdb csaf_mongodb_db csaf_wackopicko_etc csaf_wackopicko_mysql csaf_wackopicko_web
docker rmi csalab/csaf-purpleops:latest
docker-compose pull purpleops
docker-compose up -d
```

Wait a minute and see the result.

**Comment by phanikumarvarikuti** [comment]
thanks for support purpleops was working but wackpicko was not opening? please find the logs screenshot.  
![image](https://github.com/csalab-id/csaf/assets/131241288/5c2b2dd8-8473-41cc-9faa-20e1f8f1e6b5)

**Comment by redhawkeye** [comment]
Wackopicko service is working fine here. Please ensure you are in the right way.
Open http://wackopicko.lab/ in an attack environment like this.
<img width="1552" alt="wackopicko" src="https://github.com/csalab-id/csaf/assets/90817826/9ed9d556-ec97-4a0d-9bba-4a8380c04e28">
In this case, you should ensure you are not using HTTPS for the Wackopicko service.

**Comment by phanikumarvarikuti** [comment]
thanks all good working fine now.
